version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: kms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cosmian-kms:
    image: ghcr.io/cosmian/kms:latest
    container_name: kms
    entrypoint: ["/bin/cosmian_kms"]
    command: []
    ports:
      - "9998:9998"
    volumes:
      - cosmian-kms:/root/cosmian-kms/sqlite-data
    networks:
      - kms-network
    environment:
      - KMS_SQLITE_PATH=/root/cosmian-kms/sqlite-data

volumes:
  postgres_data:
  cosmian-kms:

networks:
  kms-network:
    driver: bridge
